var elements = [
	"Accusations of St George Superiority",
  "Procedural Showboating",
  "Discussion of Privilege",
  "Chair gets challenged",
  "Personal copy of Roberts Rules seen",
  "Criticism of new proxy system",
  "Dramatic exit",
  "Abrupt Adjournment",
  "Vuvuzela!",
  "Chair threatens to kick someone out",
  "Uncomfortable silence",
  "Motion to recess",
  "Technical Difficulties",
  "Anti-Harper sentiment",
  "Pierre Harfouche",
  "Mention of a lawsuit",
  "Shawn Desman is mentioned",
  "Someone starts a frosh cheer",
  "Premature BINGO!",
  "Tears",
  "Room is full",
  "Samosas run out before start of motions",
  "CFS is mentioned",
  "Inappropriate pun",
	"Throwaway war on Twitter",
	"Someone references Ashkon",
	"Someone orders a pizza"
];
